version: '3'

networks:
  mysql-network:
    driver: bridge
  nginx-network:
    driver: bridge

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    container_name: nginx
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - nginx-network

  app:
    build: 
      context: ./node
      dockerfile: ./Dockerfile
    container_name: app
    tty: true
    command: node index.js
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - nginx-network
      - mysql-network

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    command: --innodb-use-native-aio=0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodedb
    networks:
      - mysql-network